Bug Fix: Categorical Variables
Using `hasattr(,'cat')` instead of `.dtype=='category'`
In [171]: try:
   .....:     np.dtype("category")
   .....: except TypeError as e:
   .....:     print("TypeError: " + str(e))
   .....:
TypeError: data type "category" not understood

In [172]: dtype = pd.Categorical(["a"]).dtype

In [173]: try:
   .....:     np.dtype(dtype)
   .....: except TypeError as e:
   .....:      print("TypeError: " + str(e))
   .....:
TypeError: data type not understood